// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = _isStaging()
      ? FirebaseOptions(
          apiKey: 'AIzaSyBOaxwt0b3h99XJeb5BF2jMJol69sIwYkI',
          appId: '1:710372937018:web:b4f7f26e6425905113d403',
          messagingSenderId: '710372937018',
          projectId: 'narwhal-flutter',
          authDomain: 'narwhal-staging.ics.com',
          storageBucket: 'narwhal-flutter.firebasestorage.app',
          measurementId: 'G-H7W4TYBMLD',
        )
      : const FirebaseOptions(
          apiKey: "AIzaSyBOaxwt0b3h99XJeb5BF2jMJol69sIwYkI",
          authDomain: "narwhal.ics.com",
          projectId: "narwhal-flutter",
          storageBucket: "narwhal-flutter.firebasestorage.app",
          messagingSenderId: "710372937018",
          appId: "1:710372937018:web:295df272ee7a4e6213d403",
          measurementId: "G-M9H6KPEE4Y");

  static bool _isStaging() {
    // Detect staging or beta channel environment
    if (kIsWeb) {
      return Uri.base.host.contains('narwhal-staging.ics.com') ||
          Uri.base.host.endsWith('narwhal-flutter-staging.web.app') ||
          Uri.base.host.endsWith('narwhal-flutter-staging.firebaseapp.com');
    }
    return false; // Default to production
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANi-bxT-rkAQ1cGWycUUa6RyjTk6r_Llo',
    appId: '1:821985197574:android:e3278d61b9b833bf6b4d87',
    messagingSenderId: '821985197574',
    projectId: 'canvas-23f87',
    storageBucket: 'canvas-23f87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvtNL4pnhpQR5x0n7lui8w8mLeo1rPnDc',
    appId: '1:821985197574:ios:7b31fb5d763100bd6b4d87',
    messagingSenderId: '821985197574',
    projectId: 'canvas-23f87',
    storageBucket: 'canvas-23f87.firebasestorage.app',
    iosClientId:
        '821985197574-bc2i6mboh12434m20233udh71bdvcrst.apps.googleusercontent.com',
    iosBundleId: 'com.example.narwhalFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlCQxFS_c7NtD2sjrOphnu_OCyBd3p9g4',
    appId: '1:710372937018:ios:4aff011a8dd5243113d403',
    messagingSenderId: '710372937018',
    projectId: 'narwhal-flutter',
    storageBucket: 'narwhal-flutter.firebasestorage.app',
    iosClientId:
        '710372937018-bgobil2ikugu3p8tq3s5gee5rq90llm8.apps.googleusercontent.com',
    iosBundleId: 'com.example.narwhalFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOaxwt0b3h99XJeb5BF2jMJol69sIwYkI',
    appId: '1:710372937018:web:295df272ee7a4e6213d403',
    messagingSenderId: '710372937018',
    projectId: 'narwhal-flutter', // Fixed: was 'canvas-23f87'
    authDomain: 'narwhal.ics.com',
    storageBucket: 'narwhal-flutter.firebasestorage.app',
    measurementId: 'G-M9H6KPEE4Y',
  );
}
